name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: true
        default: 'macos-latest'
        type: choice
        options:
          - 'macos-latest'
          - 'windows-latest'

env:
  pnpm: 9.4.0

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: windows-latest
            arch: x86_64
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Release:MacOS
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: Release:Windows
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      - name: Release:Publish
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
