name: Release

on:
  push:
    branches:
      - master

env:
  pnpm: 9.4.0

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Install dependencies
        run: pnpm install

      - name: Release:Linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build:linux

      - name: Release:MacOS
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: Release:Windows
        if: matrix.os == 'macos-latest'
        run: pnpm build:win

      - name: Release:Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
