name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch

env:
  pnpm: 9.4.0

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0

      - name: Cache .pnpm-store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node=v20.14.0-${env.pnpm}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: npm i -g pnpm@${{env.pnpm}}

      - name: Install dependencies
        run: pnpm install

      - name: Release:MacOS
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: Release:Windows
        if: matrix.os == 'macos-latest'
        run: pnpm build:win

      - name: Release:Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
